spring.application.name=Scroll
spring.cloud.gcp.project-id=scroll-29988
spring.cloud.gcp.credentials.location=classpath:firebase-key.json
gcp.storage.bucket-name=scroll-29988.firebasestorage.app
# Disabilitiamo temporaneamente Spring Security per permettere l'upload libero
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# Aumenta il limite per il singolo file (es. 50MB)
spring.servlet.multipart.max-file-size=50MB
# Aumenta il limite per l'intera richiesta (es. 50MB)
spring.servlet.multipart.max-request-size=50MB