spring.application.name=Scroll
spring.cloud.gcp.project-id=scroll-29988
spring.cloud.gcp.credentials.location=classpath:firebase-key.json
gcp.storage.bucket-name=scroll-29988.firebasestorage.app

# --- GESTIONE FILE ---
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# --- SICUREZZA (FIREBASE JWT) ---
# Sostituisci l'URL con il project-id esatto del tuo progetto Firebase.
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/scroll-29988

spring.mail.host=smtps.aruba.it
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true